name: CI/CD DCC072

on: [push, pull_request]

jobs:
    test:
        strategy:
            matrix: 
                os: [ubuntu-latest, windows-latest, macos-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python 
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Run Tests
              run: python parking_lot_tests.py